apiVersion: v1
kind: Service
metadata:
  name: quicknews-backend-main
spec:
  type: NodePort
  selector:
    app: quicknews-backend-main
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30001 # Optional, Kubernetes will automatically assign a port if not specified
