version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/quicknews-backend/
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: /pipelines/pipelines/integrations-deployment-pre-post.sh
